// LISTS
export const LIST_REQUESTED = 'LIST_REQUESTED';
export const LIST_RECEIVED = 'LIST_RECEIVED';
export const LIST_ERRORED = 'LIST_ERRORED';

// ITEMS
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const INIT_NEW_ITEM = 'INIT_NEW_ITEM';
export const ITEM_REQUESTED = 'ITEM_REQUESTED';
export const ITEM_RECEIVED = 'ITEM_RECEIVED';
export const ITEM_ERRORED = 'ITEM_ERRORED';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';
export const SHOW_SHARING_DIALOG = 'SHOW_SHARING_DIALOG';
export const HIDE_SHARING_DIALOG = 'HIDE_SHARING_DIALOG';

// PAGER
export const PAGER_RESET = 'PAGER_RESET';

// FILTER
export const FILTER_UPDATED = 'FILTER_UPDATED';
export const FILTER_RESET = 'FILTER_RESET';

// CURRENT USER
export const INIT_CURRENT_USER = 'INIT_CURRENT_USER';
export const CURRENT_USER_GROUP_MEMBERSHIP_REQUESTED =
    'CURRENT_USER_GROUP_MEMBERSHIP_REQUESTED';
export const CURRENT_USER_GROUP_MEMBERSHIP_RECEIVED =
    'CURRENT_USER_GROUP_MEMBERSHIP_RECEIVED';
export const CURRENT_USER_GROUP_MEMBERSHIP_ERRORED =
    'CURRENT_USER_GROUP_MEMBERSHIP_ERRORED';
