// USER
export const LIST_REQUESTED = 'USER_LIST_REQUESTED';
export const LIST_ERRORED = 'USER_LIST_ERRORED';

export const USER_LIST_RECEIVED = 'USER_LIST_RECEIVED';
export const USER_ROLE_LIST_RECEIVED = 'USER_LIST_RECEIVED';
export const USER_GROUP_LIST_RECEIVED = 'USER_LIST_RECEIVED';

export const PAGE_INCREMENTED = 'USER_LIST_PAGE_INCREMENTED';
export const PAGE_DECREMENTED = 'USER_LIST_PAGE_DECREMENTED';
export const PAGER_RESET = 'PAGER_RESET';

export const FILTER_UPDATED = 'FILTER_UPDATED';
export const FILTER_RESET = 'FILTER_RESET';
export const FILTER_RESET_FOR_USER = 'FILTER_RESET_FOR_USER';
