// LISTS
export const LIST_REQUESTED = 'LIST_REQUESTED';
export const LIST_ERRORED = 'LIST_ERRORED';

export const USER_LIST_RECEIVED = 'USER_LIST_RECEIVED';
export const USER_ROLE_LIST_RECEIVED = 'USER_LIST_RECEIVED';
export const USER_GROUP_LIST_RECEIVED = 'USER_LIST_RECEIVED';

// ITEMS
export const ITEM_REQUESTED = 'ITEM_REQUESTED';
export const ITEM_ERRORED = 'ITEM_ERRORED';

export const USER_ITEM_RECEIVED = 'USER_ITEM_RECEIVED';
export const USER_ROLE_ITEM_RECEIVED = 'USER_ITEM_RECEIVED';
export const USER_GROUP_ITEM_RECEIVED = 'USER_ITEM_RECEIVED';

// PAGER
export const PAGE_INCREMENTED = 'USER_LIST_PAGE_INCREMENTED';
export const PAGE_DECREMENTED = 'USER_LIST_PAGE_DECREMENTED';
export const PAGER_RESET = 'PAGER_RESET';

// FILTER
export const FILTER_UPDATED = 'FILTER_UPDATED';
export const FILTER_RESET = 'FILTER_RESET';
export const FILTER_RESET_FOR_USER = 'FILTER_RESET_FOR_USER';
